name: Deploy my website in DeployHQ w/ my webhook URL
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    # Put steps here to build your site, deploy it to a service, etc.
    - name: Trigger deployment in DeployHQ w/ webhook URL
      uses: deployhq/deployhq-action@main
      env:
        # All these values should be set as encrypted secrets in your repository settings
        DEPLOYHQ_WEBHOOK_URL: ${{ secrets.DEPLOYHQ_WEBHOOK_URL }}
        REPO_REVISION: ${{ secrets.REPO_REVISION }}
        REPO_BRANCH: ${{ secrets.REPO_BRANCH }}
        DEPLOYHQ_EMAIL: ${{ secrets.DEPLOYHQ_EMAIL }} 
        REPO_CLONE_URL: ${{ secrets.REPO_CLONE_URL }}
